language: ruby
dist: trusty
cache: bundler

language: ruby
cache: 
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
cache: bundler

jobs:
  include:
    - script: bundle exec rake test
    - script: bundle exec rubocop
      rvm: 2.6
